### ISSUE TITLE
Discrepancy between house load and power used from source

### ISSUE THREAD

**Issue by thibodelanghe** [NosIreland/solismon3#10]
Hi there

Im using this piece of code and it works quite well! 

I currently have the problem that the total capacity of pv + solar panels differs from the house load. for example. 

The battery provides 266W, PV generates 2 watts and the house load is 192. There is a difference of (266+2-192) 76W. That difference is also not taken from the grid. 

Does anyone know what is causing this?

**Comment by alienatedsec** [comment]
@thibodelanghe the inverter needs to be powered too. Without batteries, it would turn off and turn back on when enough PV generation. The only downside of that is regardless of PV GENERATION it will always use batteries when those are fully charged.

**Comment by thibodelanghe** [comment]
@alienatedsec yeah, i thought so.. Just checking so i don't break my head over it. Thanks for the quick reply!
