### ISSUE TITLE
Serialnumber not an Integer and S2-WL-ST support

### ISSUE THREAD

**Issue by schorges** [NosIreland/solismon3#12]
Not an Inter with the "A" on S2-Stick
S2-WL-ST 4-pin dual WiFi/LAN stick: Serial number 7Axxxxxxxxxxxxxx****
How can i fix that? "7A123456789" not work

**Comment by alienatedsec** [comment]
The S2-WL-ST datalogger is not compatible with the Solarman protocol so the solismon3 project won't work. 

You can read more here https://github.com/alienatedsec/solis-ha-modbus-cloud
