### ISSUE TITLE
Help with registers

### ISSUE THREAD

**Issue by alienatedsec** [NosIreland/solismon3#4]
Hi @NosIreland 

I have `SOLIS RHI-6K-48ES-5G`, and some default registers provide data for the previous day but claim its today's data.
Example
```
(33161, (
        ('today_imported_energy', 'Today Imported Energy(0.1kWh)'),
```
The above provides yesterday's imported energy instead of today's.  I scanned the datalogger with `register_scan.py` but I would not even know where to start or how to approach the subject to correct this. I am happy to contribute and produce the `registers.py` for this model with some help.

**Comment by alienatedsec** [comment]
I found the issue - the below commit moved a series of data by 1 "column" ahead 
https://github.com/slayer1551/solismon-3/commit/9bb42e58c721ad3b960be98c6ea4822cd3feb1b0

Unfortunately, it is wrong

**Comment by NosIreland** [comment]
@alienatedsec The registers differ based on inverter model and firmware version. The ones provided are the ones that work with my inverter.

**Comment by alienatedsec** [comment]
They work with mine too; however, I am still wondering how to read those outputs from the `register_scan.py`?
@NosIreland

**Comment by NosIreland** [comment]
`register_scan.py` just goes through the range of registers defined and checks if it gets an output. Unfortunantly it will be upto user to figure out what the output corresponds to. Some are obvious where as other ones are not.
