### ISSUE TITLE
tesla-style-solar-power-card config

### ISSUE THREAD

**Issue by jasonmadigan** [NosIreland/solismon3#5]
hey @NosIreland - wondered if you could share your config for tesla-style-solar-power card (specifically, what maps to what). Have had it setup for a few weeks now and all works fine, but there's some strangeness when charging to the grid where I see grid usage double that I'm trying to narrow down, and I think if I had an example I'd be able to spot what's up. Thanks!

**Comment by NosIreland** [comment]
Here is my config. There is some strange behaviour with the card. I think this is because it does not accept negative values.
```
type: custom:tesla-style-solar-power-card
grid_consumption_entity: sensor.meter_power_in_modified
grid_to_house_entity: sensor.meter_power_in_modified
house_consumption_entity: sensor.total_load_power_modified
grid_to_battery_entity: sensor.grid_to_battery_power_in_modified
generation_to_grid_entity: sensor.meter_power_out_modified
generation_to_battery_entity: sensor.battery_power_in_modified
generation_to_house_entity: sensor.solar_to_house_power_modified
battery_to_house_entity: sensor.battery_power_out_modified
battery_extra_entity: sensor.battery_capacity_soc
appliance1_consumption_entity: sensor.bypass_load_power
appliance1_icon: mdi:server-network
generation_icon: mdi:solar-power
house_extra_entity: sensor.house_load_today
generation_extra_entity: sensor.generated_today
grid_extra_entity: sensor.imported_today
grid_entity: sensor.meter_power_in_modified
house_entity: sensor.total_load_power_modified
generation_entity: sensor.total_solar_output_power
battery_entity: sensor.battery_capacity_soc
```

**Comment by jasonmadigan** [comment]
thanks a lot @NosIreland  - yeah, I think that's probably at the root of the oddness I'm seeing as well.

**Comment by jasonmadigan** [comment]
One question (since I think I'm missing a sensor) - what is `sensor.total_solar_output_power`? Maybe it's a custom register, didn't spot it in `registers.py`.

**Comment by NosIreland** [comment]
> 

It is custom sensor defined in home-assistant `configuration.yaml` . In my case it is the same as `sensor.total_dc_input_power_2` since I only have one string of panels attached.  Others who have multiple strings it could be used to sum multpiple strings into single sensor.
