### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kuttikutt** [NosIreland/solismon3#8]
why I try to run the main.py I get: 

```
python2.7 main.py
  File "main.py", line 69
    logging.error(f'{repr(e)}. Exiting')
                                      ^
SyntaxError: invalid syntax
```

any ideas?

**Comment by kuttikutt** [comment]
nevermind - just figured out that my WiFi stick isn't compatible anyway. What a pitty :/

**Comment by alienatedsec** [comment]
I don't have the same datalogger - you mentioned it [here](https://github.com/hultenvp/solis-sensor/discussions/100#discussioncomment-5008501); however, you need to meet requirements and install those modules
```
umodbus
paho-mqtt
prometheus-client
pysolarmanV5
```

Also, when you run the `main.py`, execute with `python3`

`python3 main.py`
